name: CI/CD - Build, Push, Deploy

on:
  push:
    branches: [main]
    paths:
      - 'app/**'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-fastapi:${{ github.sha }}

      - name: Update Config Repo
        run: |
          git clone https://x-access-token:${{ secrets.CONFIG_REPO_TOKEN }}@github.com/u6t65k6/argocd-config.git
          cd argocd-config
          sed -i "s|image: .*/docker-fastapi:.*|image: ${{ secrets.DOCKER_USERNAME }}/docker-fastapi:${{ github.sha }}|" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "chore: update image to ${{ github.sha }}"
          git push
